# Generated by Django 4.0.6 on 2023-07-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetTestHost',
        ),
    ]
